version: "3.9"

services:
  worker:
    image: ghcr.io/nyetii/kimi:latest
    container_name: kimi
    restart: always

    volumes:
      - kimi-data:/app/kimi/data
      - config:/app/kimi/config

    environment:
      ConnectionStrings__Default: "Data Source=/app/kimi/data/Kimi.db"

volumes:
  kimi-data:
    type: none
    device: /app/kimi/data
    o: bind
  config: